version: 0.0
os: linux
files:
  - source: /
    destination: /root/file_sharing_service
    overwrite: yes
    exclude:
      - app/**
file_exists_behavior: OVERWRITE
permissions:
  - object: /root/file_sharing_service
    pattern: "**"
    owner: root
    group: root
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root
